change web search
osmandapp/OsmAnd-tools pull request #885
Opened 2024-08-08 11:24 UTC by alisa911

2024-08-08 11:24 UTC, alisa911 commented
https://github.com/osmandapp/web/issues/432

2024-08-12 13:41 UTC, RZR-UA requested changes

2024-08-12 13:41 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchService.java
> +        searchUICore.setTotalLimit(1000);
please avoid magic values

2024-08-12 13:41 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/SearchService.java
> +        Map<String, String> phrases = Algorithms.parseStringsXml(new File(andTranslationsLocation + localPath + "/phrases.xml"));
dangerous File access (externally-defined by locale string). should be sanitized. at minimum, remove '/' chars from `locale`

2024-08-12 13:41 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/resources/application.yml
> +  android.translations.location: ${osmand.files.location}/android/OsmAnd/res/
osmand.files.location: /var/www-download

there is no `/android/OsmAnd/res/` in the specified directory

please think another way to get the resources and refresh them regularly

possible path is workspace of Jenkins WebSite_UpdateFrontend job (depened to Web updates...)

2024-08-13 17:31 UTC, RZR-UA approved these changes

2024-08-15 08:04 UTC, RZR-UA commented
- [ ] https://test.osmand.net/routing/search/get-poi-address?lat=48.17473&lon=24.437403 fix 400 "Error get poi address!" (error is reported in browser)

2024-08-15 08:07 UTC, RZR-UA commented
- [ ] fix divide by zero error

```
curl 'https://test.osmand.net/routing/search/search-poi?locale=en' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://test.osmand.net/map/search/' -H 'Content-Type: application/json' -H 'Origin: https://test.osmand.net' -H 'Connection: keep-alive' -H 'Cookie: email=youonly%40ukr.net; XSRF-TOKEN=c4f2ae4f-7e7d-4dc7-90a6-71d6d072f80d; JSESSIONID=2B920FB7DF0ADAC56D8D8BB5252B9087' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: same-origin' -H 'Priority: u=4' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"categories":[],"northWest":"48.237308654125236,24.481573104858402","southEast":"48.182684785134384,24.618902206420902","savedNorthWest":"48.23565029755308,24.29386138916016","savedSouthEast":"48.12634074841738,24.568519592285156","prevCategoriesCount":null}'
```

```
java.lang.ArithmeticException: / by zero
        at net.osmand.server.api.services.SearchService.searchPoi(SearchService.java:164)
        at net.osmand.server.controllers.pub.SearchController.searchPoi(SearchController.java:67)
        at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
```

2024-08-16 09:58 UTC, RZR-UA approved these changes

2024-08-19 11:41 UTC, vshcherb commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/OsmAndMapsService.java
> -		ConcurrentHashMap<BinaryMapIndexReader, Boolean> readers = new ConcurrentHashMap<>();
too complicated we should reuse readers for all locales

2024-08-19 16:02 UTC, ivanPyrohivskyi approved these changes

2024-08-20 07:37 UTC, merged