add wiki metadata parser
osmandapp/OsmAnd-tools pull request #923
Opened 2024-10-04 08:49 UTC by alisa911

2024-10-04 08:50 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2705

2024-10-04 10:04 UTC, RZR-UA requested changes

2024-10-04 10:04 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/SearchController.java
> +        if (data != null) {
Combile old parsing with the POST rawData from new parsing.

2024-10-04 10:04 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/utils/MultiPlatform.java
> +}
How this file is connected with Wiki Metadata Parser?

2024-10-07 10:54 UTC, RZR-UA approved these changes

2024-10-10 10:37 UTC, vshcherb commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/WikiService.java
> +		String query = "INSERT INTO wiki.imagesrawdata (url, raw_data) VALUES (?, ?)";
Probably better to rename to something more related to wikimedia naming 
commonswiki_cache (pageid, title, data)

2024-10-11 12:00 UTC, RZR-UA requested changes

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java
>  				"http://" + lang + ".wikpedia.org/wiki/${title}", null, true);
Should be https://

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java
>  										"http://" + lang + ".wikpedia.org/wiki/${title}", imageUrlStorage, true);
Should be https://

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java
> +		String regex = "\\[(http\\S+)\\s([^]]+)]";
Is http**s**: parsing supported? `https? httpx? http/`? Additionally, weird part of regexp [^]] should be clarified. It is better to refactor this regexp from scratch.

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/SearchController.java
> +        }
The cache becomes vulnerable with this block.

Anyone now is able to poison the cache with any data.

For example, poison with URL(s) of fishing / porn sites and/or invalid content which could lead server to crash.

It is better to remove this block completely or add strong validation of the sender (token, deviceid, etc).

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/SearchController.java
> +                wikiService.saveWikiRawDataToCache(title, pageId, rawData);
Another case of cache vulnerability.

2024-10-11 12:00 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/WikiService.java
> +		String urlStr = "https://commons.wikimedia.org/wiki/File:" + encodedImageTitle + "?action=raw";
Please implement strong validation of `imageTitle` to avoid arbitrary requests caused by user-defined parameter.

2024-10-11 13:45 UTC, merged