use kotlin lib
osmandapp/OsmAnd-tools pull request #966
Opened 2024-11-12 14:54 UTC by alisa911

2024-11-12 15:05 UTC, alisa911 commented
https://github.com/osmandapp/OsmAnd-Issues/issues/2708

2024-11-12 17:36 UTC, RZR-UA requested changes
Finally,

1) merge the freshest master into your branch

2) deploy your branch on creator and test all features with "yarn test:test" (run full UI test)

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/RoutingService.java
> +            kotlinBundle.putString(key, value);
Possibly, avoid putString() if value == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/GpxController.java
> +	public ResponseEntity<Resource> getGpx(@RequestParam String name, HttpSession httpSession) {
required = true or NPE (at least incorrect equals) at line 113 ?

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/GpxController.java
> +		if (gpxFile.getError() != null) {
NPE if try {} failed

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/pub/OsmGpxController.java
>  		if (!points.isEmpty() && points.size() > 100 && analysis.getMaxDistanceBetweenPoints() < 1000) {
Please reuse constants from DownloadOsmGPX

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/FavoriteController.java
>          if (file != null) {
Add && xxx.getError() == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/FavoriteController.java
>          if (file != null) {
Add && xxx.getError() == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/FavoriteController.java
>          if (newGpxFile != null) {
Add && xxx.getError() == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/FavoriteController.java
>              if (oldGpxFile != null) {
always != null, so add && xxx.getError() == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/FavoriteController.java
>          if (gpxFile != null) {
Add && xxx.getError() == null

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
> +						if (gpxFile.getError() != null) {
NPE if try {} failed

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
> +			if (gpxFile.getError() != null) {
NPE if try {} failed

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
> +			if (gpxFile.getError() != null) {
NPE if try {} failed

2024-11-12 17:36 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/api/services/GpxService.java
>          }
Please wrap it into `if (gpxFileForAnalyse.getError() == null)`

2024-11-13 08:21 UTC, RZR-UA commented on java-tools/OsmAndServer/src/main/java/net/osmand/server/controllers/user/MapApiController.java
> +							LOG.error("Error reading gpx file: " + uf.name + " (id=" + uf.id + ") (userid=" + uf.userid + ")");
LOG.error("web-list-files: loadGpxFile error: " + uf.name + " (id=" + uf.id + ") (userid=" + uf.userid + ")");

please use similar keywords in message to make it "greppable" easier in the logs (grep "web-list-files" ...)

2024-11-13 08:41 UTC, RZR-UA approved these changes

2024-11-13 12:01 UTC, RZR-UA approved these changes

2024-11-13 13:15 UTC, merged